version: '3'

services: 
  godb:
    image: mysql:5.7
    container_name: dddstudy
    environment: 
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${USER_PASS}
      MYSQL_DATABASE: ${USER_DB}
      TZ: ${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
